### ISSUE TITLE
"How would you rate your experience" dropdowns are missing the star ratings (no way to provide the requested feedback)

### ISSUE THREAD

**Issue by dholbert** [mozilla/pulse#179] opened 2017-06-04 00:40 UTC
Over the past few days, the periodic "How would you rate your experience" dropdown bars (which I think come from Pulse) have no visible stars, in my Nightly.  So there's no way to provide the requested feedback.
 
See attached screenshot:
![selection_002](https://cloud.githubusercontent.com/assets/426803/26757955/4deee0ba-4883-11e7-90c3-d4c5d66ef4a1.png)

I'm running Nightly 55.0a1 (2017-06-03) (64-bit) on Ubuntu 17.04 with the Compact Dark built-in browser theme and the [System76 "Pop" GTK theme](http://www.omgubuntu.co.uk/2017/04/system76-pop-gtk-theme-ubuntu). (not sure if it's relevant but just in case)

**Comment by dholbert** [comment] 2017-06-04 00:42
Is there a way I can trigger this notification to appear on-demand?  I haven't been really able to investigate what might be causing the issue, because the prompts appear so infrequently/randomly.  But if I could make them appear, I could try to isolate what part of my configuration is causing the stars to be missing (assuming that this isn't a universal issue).

**Comment by chuckharmston** [comment] 2017-06-05 17:29
Thanks for the report!

This is likely a regression due to upstream changes from Photon; I'll look into it before troubling you with investigation into your configuration 🙂

**Comment by chuckharmston** [comment] 2017-06-08 16:06
@dholbert Unfortunately, I have not been able to reproduce this. I’d like to take you up on your offer to help find the conditions that lead to it, if you’d be so kind.

Here’s [a custom build](https://github.com/mozilla/pulse/files/1061600/addon.zip) that shortens the fuse on the prompt; it will prompt every 30 seconds so long as the focused tab and window are `http` or `https`.

I suspect that this is due to some platform-specific CSS, likely related to Photon changes. Some variables that would be helpful to isolate:

- Release channel (comparing to Beta would be helpful)
- Theme
- Operating system (if possible; I’ve already tried each of macOS, Linux, and Windows)

Additionally:

- If you are able to try to isolate the CSS rule causing the stars to be hidden (if it exists), that’d be amazing.
- The browser console may have relevant errors. Those would be great to discover, as well.

Thanks in advance for the assist!

**Comment by dholbert** [comment] 2017-06-08 17:28
Thanks! With that custom build of the extension:
 - I was able to confirm that I can reproduce this bug in a "clean" Ubuntu environment (in a mostly-untouched VM that I use for testing).  Hopefully that means you could reproduce as well, in an Ubuntu environment!
 - I was able to track down a [regression range](https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=38d34be6d67446b9f6241cef1d7188310c28c426&tochange=9cdcc98ab24ab61fae5317245c7e1676f837b9d0) -- this regressed from [bug 1366005](https://bugzilla.mozilla.org/show_bug.cgi?id=1366005), whose changesets indeed deleted some icons called "[heartbeat-star-off.svg](https://hg.mozilla.org/integration/autoland/diff/48a6570b38cb/browser/themes/shared/heartbeat-star-off.svg)" and "[heartbeat-star-lit.svg](https://hg.mozilla.org/integration/autoland/diff/48a6570b38cb/browser/themes/shared/heartbeat-star-lit.svg)".  Maybe those were the icons that the extension is using? Or maybe one of that bug's other removed/moved files is involved here somehow.
 - Also, I checked the error console and didn't see any errors that looked related to this extension.

**Comment by dholbert** [comment] 2017-06-08 17:40
If I inspect the star-buttons in a build from before the regression, I see that the star is painted via this CSS rule from `browser.css`:
````
.heartbeat > #star-rating-container > .star-x {
    background: url("chrome://browser/skin/heartbeat-star-off.svg");
    cursor: pointer;
    margin-inline-end: 4px !important;
    width: 16px;
    height: 16px;
}
````

In a build from *after* the regression, the stars do not have that CSS applied. (I don't see it in the browser toolbox inspector Rules view anymore.)

It looks like this precise CSS was indeed moved between files in bug 1366005:
It was removed from "UITour.inc.css" (which I assume gets compiled into browser.css) here:
  https://hg.mozilla.org/mozilla-central/rev/48a6570b38cb#l5.137
And it was added back to a very-different file ("browser/extensions/shield-recipe-client/skin/shared/Heartbeat.css") here:
 https://hg.mozilla.org/mozilla-central/rev/9cdcc98ab24a#l4.123

So presumably Pulse needs to be updated to find this star CSS in its new location (if it can - not sure whether extensions can borrow from each other).  Or perhaps it should bring the star images/styling along itself?  Or perhaps we should partly-revert bug 1366005 so that multiple extensions can share these resources, if that's the intent?

Anyway, hopefully that's enough for you to go on. :) Ball's back in your court now. Thanks again for the custom build.

**Comment by Caspy7** [comment] 2017-06-12 12:46
I have seen this too.
I'm on Nightly, win10, also compact dark theme.

**Comment by chuckharmston** [comment] 2017-06-12 12:46
\+ IRC report of this on Win10.

**Comment by bunnybooboo** [comment] 2017-06-23 08:58
Reproduced. Nightly on Arch Linux. Compact Dark theme.

**Comment by mythmon** [comment] 2017-06-23 16:12
> So presumably Pulse needs to be updated to find this star CSS in its new location (if it can - not sure whether extensions can borrow from each other). Or perhaps it should bring the star images/styling along itself? Or perhaps we should partly-revert bug 1366005 so that multiple extensions can share these resources, if that's the intent?

I think that Pulse should have it's own copy of these images, instead of relying on another part of code to have them. We can't guarantee that Shield will always be present and providing those exact same assets, as we are also developed outside of mozilla-central, and don't have visibility into other code bases, like Pulse's.

**Comment by chuckharmston** [comment] 2017-06-23 16:18
Pulse will be retiring the week after the all-hands, so I'm going to close this as a wontfix rather than try to keep up with Photon-related changes.

Thanks for the report!

**Closed as completed by chuckharmston** 2017-06-23 16:18 UTC
