### ISSUE TITLE
The "Pulse" icon and rating stars are not visible when enabling High Contrast White OS theme on Windows

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/pulse#147] opened 2017-03-29 14:58 UTC
[Affected versions]:
- Firefox 52.0 and up
- Pulse 1.1 RC 

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Pulse v1.1 RC was previously installed on a clean profile.
- High Contrast White OS theme on Windows is enabled.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and navigate to any http or https website.
2. Click on the "Pulse" button from the URL bar.
3. Check if all the items are visible.

[Expected result]:
- The text, "Pulse" icon and rating stars are visible.

[Actual result]:
- The "Pulse" icon and rating stars are not visible.

[Notes]:
- Hovering the rating stars area changes the mouse's arrow into the pointer hand.
- Clicking an invisible star opens the "Submit" panel. 
- Please see the Screen Cast attached:

![white](https://cloud.githubusercontent.com/assets/26000308/24461092/cdc7e53e-14a8-11e7-9d99-fe54408c399f.gif)

**Comment by chuckharmston** [comment] 2017-03-29 15:46
To centralize similar discussion, I'm going to close this as a duplicate of https://github.com/mozilla/pulse/issues/147.

**Closed as completed by chuckharmston** 2017-03-29 15:46 UTC
